name: Random Daily Commits

on:
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make random number of commits
        run: |
          NUMBER_OF_COMMITS=$((RANDOM % 6 + 1))
          for i in $(seq 1 $NUMBER_OF_COMMITS)
          do
            echo "Update $i on $(date)" >> README.md
            git add README.md
            COMMIT_MESSAGE=$(git log --since=midnight --until=now --oneline | shuf -n 1 | cut -d' ' -f2-)
            if [ -z "$COMMIT_MESSAGE" ]; then
              COMMIT_MESSAGE="Update on $(date)"
            fi
            git commit -m "$COMMIT_MESSAGE"
          done